import javax.swing.*;
import java.sql.*;
import javax.swing.JFrame;

public class ManageExeiForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageExeiForm
     */
    public ManageExeiForm() {
        initComponents();
        myconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBackToMenuExei = new javax.swing.JButton();
        jButtonInsertToExei = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStafftID = new javax.swing.JTextField();
        jButtonResetManageExei = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDoctorID = new javax.swing.JTextField();
        jButtonUpdateFromExei = new javax.swing.JButton();
        jButtonDeleteFromExei = new javax.swing.JButton();
        jTextFieldStafftNewID = new javax.swing.JTextField();
        jTextFieldDoctorNewID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Διαχείριση Στοιχείων του Πίνακα Έχει");

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMinimize))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(723, 432));

        jButtonBackToMenuExei.setBackground(new java.awt.Color(149, 165, 166));
        jButtonBackToMenuExei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackToMenuExei.setForeground(new java.awt.Color(242, 38, 19));
        jButtonBackToMenuExei.setText("Επιστροφή στο Menu του Πίνακα Έχει");
        jButtonBackToMenuExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackToMenuExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToMenuExeiActionPerformed(evt);
            }
        });

        jButtonInsertToExei.setBackground(new java.awt.Color(34, 167, 240));
        jButtonInsertToExei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInsertToExei.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertToExei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonInsertToExei.setText("Εισαγωγή");
        jButtonInsertToExei.setToolTipText("ΠΡΟΣΟΧΗ!!! Δε χρειάζεται να συμπληρώσετε ΜΟΝΟ τα 2 πρώτα πεδία!!!");
        jButtonInsertToExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsertToExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertToExeiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("ID Προσωπικού:");

        jTextFieldStafftID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldStafftID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldStafftID.setForeground(new java.awt.Color(228, 241, 254));

        jButtonResetManageExei.setBackground(new java.awt.Color(242, 38, 19));
        jButtonResetManageExei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResetManageExei.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResetManageExei.setText("Reset");
        jButtonResetManageExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonResetManageExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetManageExeiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("ID Γιατρού:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("ID Προσωπικού (Ενημέρωση):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("ID Γιατρού (Ενημέρωση):");

        jTextFieldDoctorID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldDoctorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDoctorID.setForeground(new java.awt.Color(228, 241, 254));

        jButtonUpdateFromExei.setBackground(new java.awt.Color(34, 167, 240));
        jButtonUpdateFromExei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateFromExei.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateFromExei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButtonUpdateFromExei.setText("Ενημέρωση");
        jButtonUpdateFromExei.setToolTipText("ΠΡΟΣΟΧΗ!!! Η Ενημέρωση γίνεται με βάση τα 2 πρώτα πεδία!!!");
        jButtonUpdateFromExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdateFromExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateFromExeiActionPerformed(evt);
            }
        });

        jButtonDeleteFromExei.setBackground(new java.awt.Color(34, 167, 240));
        jButtonDeleteFromExei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteFromExei.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteFromExei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonDeleteFromExei.setText("Διαγραφή");
        jButtonDeleteFromExei.setToolTipText("ΠΡΟΣΟΧΗ!!! Πρέπει να βάλετε τα ενημερωμένα IDs στη Διαγραφή!!!");
        jButtonDeleteFromExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteFromExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteFromExeiActionPerformed(evt);
            }
        });

        jTextFieldStafftNewID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldStafftNewID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldStafftNewID.setForeground(new java.awt.Color(228, 241, 254));

        jTextFieldDoctorNewID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldDoctorNewID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDoctorNewID.setForeground(new java.awt.Color(228, 241, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldStafftNewID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStafftID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDoctorNewID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(154, 154, 154))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonInsertToExei)
                .addGap(32, 32, 32)
                .addComponent(jButtonUpdateFromExei)
                .addGap(35, 35, 35)
                .addComponent(jButtonDeleteFromExei)
                .addGap(32, 32, 32)
                .addComponent(jButtonResetManageExei, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackToMenuExei)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStafftID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldStafftNewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDoctorNewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsertToExei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdateFromExei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleteFromExei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonResetManageExei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(jButtonBackToMenuExei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonResetManageExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetManageExeiActionPerformed
        jTextFieldStafftID.setText("");
        jTextFieldDoctorID.setText("");
        jTextFieldStafftNewID.setText("");
        jTextFieldDoctorNewID.setText("");
    }//GEN-LAST:event_jButtonResetManageExeiActionPerformed

    private void jButtonBackToMenuExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToMenuExeiActionPerformed
        ExeiForm ef = new ExeiForm();
        ef.setVisible(true);
        ef.pack();
        ef.setLocationRelativeTo(null);
        ef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToMenuExeiActionPerformed

    private void jButtonInsertToExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertToExeiActionPerformed
        int staffID = Integer.valueOf(jTextFieldStafftID.getText());
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        
        /*
        if((jTextFieldPatientID.getText().isEmpty()) || (jTextFieldDoctorID.getText().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Some Fields Are Empty!!!", "ERROR", 1);
        } else {
        */
        
            try {
                String insertString = "INSERT INTO Exei(IDProswpikou, IDGiatrou) values(?,?)";
                pst = dbConnection.prepareStatement(insertString);
                pst.setInt(1, staffID);
                pst.setInt(2, doctorID);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted Successfully!!!");
            } catch(SQLException ex) {
                 System.out.println("\n -- SQL Exception --- \n");
                 while(ex != null) {
                     System.out.println("Message: " + ex.getMessage());
                     ex = ex.getNextException();
                 }
             }
        // }
    }//GEN-LAST:event_jButtonInsertToExeiActionPerformed

    private void jButtonUpdateFromExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateFromExeiActionPerformed
        int staffID = Integer.valueOf(jTextFieldStafftID.getText());
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        int staffNewID = Integer.valueOf(jTextFieldStafftNewID.getText());
        int doctorNewID = Integer.valueOf(jTextFieldDoctorNewID.getText());

        try {
            String updateString = "UPDATE EXEI SET IDProswpikou=?, " +
            "IDGiatrou=? WHERE IDProswpikou=? AND IDGiatrou=?";
            pst = dbConnection.prepareStatement(updateString);
            pst.setInt(1, staffNewID);
            pst.setInt(2, doctorNewID);
            pst.setInt(3, staffID);
            pst.setInt(4, doctorID);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonUpdateFromExeiActionPerformed

    private void jButtonDeleteFromExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteFromExeiActionPerformed
        int staffNewID = Integer.valueOf(jTextFieldStafftNewID.getText());
        int doctorNewID = Integer.valueOf(jTextFieldDoctorNewID.getText());
        
        try {
            String updateString = "DELETE FROM EXEI WHERE IDProswpikou=? AND IDGiatrou=?";
            pst = dbConnection.prepareStatement(updateString);
            pst.setInt(1, staffNewID);
            pst.setInt(2, doctorNewID);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Deleted Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
                 while(ex != null) {
                     System.out.println("Message: " + ex.getMessage());
                     ex = ex.getNextException();
                 }
        }
    }//GEN-LAST:event_jButtonDeleteFromExeiActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageExeiForm().setVisible(true);
            }
        });
    }
    
    static String     driverClassName = "oracle.jdbc.OracleDriver" ;
    static String     url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs" ;
    static Connection dbConnection = null;
    static String     username = "it144172";
    static String     passwd = "j@3teJi3";
    static PreparedStatement  pst = null;
    // static ResultSet rs = null;
    
    void myconnection() {
        try { 
             Class.forName (driverClassName);
        } catch (ClassNotFoundException ex) { }
        try {    
            dbConnection = DriverManager.getConnection (url, username, passwd);
            // String insertString = "INSERT INTO Kratisi(IDAstheni, IDGiatrou, HmeromhniaKratisis, OraKratisis) values(?,?,?,?)";
            // pst = dbConnection.prepareStatement(insertString);
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToMenuExei;
    private javax.swing.JButton jButtonDeleteFromExei;
    private javax.swing.JButton jButtonInsertToExei;
    private javax.swing.JButton jButtonResetManageExei;
    private javax.swing.JButton jButtonUpdateFromExei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDoctorID;
    private javax.swing.JTextField jTextFieldDoctorNewID;
    private javax.swing.JTextField jTextFieldStafftID;
    private javax.swing.JTextField jTextFieldStafftNewID;
    // End of variables declaration//GEN-END:variables
}
