import javax.swing.*;
import java.sql.*;
import javax.swing.JFrame;

public class ManageGiatrosForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGiatrosForm
     */
    public ManageGiatrosForm() {
        initComponents();
        myconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonExitPage = new javax.swing.JButton();
        jButtonInsertToGiatros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDoctorID = new javax.swing.JTextField();
        jButtonResetManageGiatros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonUpdateFromGiatros = new javax.swing.JButton();
        jButtonDeleteFromGiatros = new javax.swing.JButton();
        jTextFieldPNumber = new javax.swing.JTextField();
        jTextFieldSpecialty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Διαχείριση Στοιχείων Γιατρού");

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMinimize))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(639, 540));

        jButtonExitPage.setBackground(new java.awt.Color(149, 165, 166));
        jButtonExitPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExitPage.setForeground(new java.awt.Color(242, 38, 19));
        jButtonExitPage.setText("Έξοδος απ' τη σελίδα");
        jButtonExitPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExitPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitPageActionPerformed(evt);
            }
        });

        jButtonInsertToGiatros.setBackground(new java.awt.Color(34, 167, 240));
        jButtonInsertToGiatros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInsertToGiatros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertToGiatros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonInsertToGiatros.setText("Εισαγωγή");
        jButtonInsertToGiatros.setToolTipText("ΠΡΟΣΟΧΗ!!! Δε χρειάζεται να βάλετε το ID Γιατρού στην Εισαγωγή!!!");
        jButtonInsertToGiatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsertToGiatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertToGiatrosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("ID Γιατρού:");

        jTextFieldDoctorID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldDoctorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDoctorID.setForeground(new java.awt.Color(228, 241, 254));

        jButtonResetManageGiatros.setBackground(new java.awt.Color(242, 38, 19));
        jButtonResetManageGiatros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResetManageGiatros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResetManageGiatros.setText("Reset");
        jButtonResetManageGiatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonResetManageGiatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetManageGiatrosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Όνομα:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Τηλέφωνο:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Ειδικότητα:");

        jTextFieldName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(228, 241, 254));

        jButtonUpdateFromGiatros.setBackground(new java.awt.Color(34, 167, 240));
        jButtonUpdateFromGiatros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateFromGiatros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateFromGiatros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButtonUpdateFromGiatros.setText("Ενημέρωση");
        jButtonUpdateFromGiatros.setToolTipText("ΠΡΟΣΟΧΗ!!! Η Ενημέρωση γίνεται με βάση το ID Γιατρού!!!");
        jButtonUpdateFromGiatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdateFromGiatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateFromGiatrosActionPerformed(evt);
            }
        });

        jButtonDeleteFromGiatros.setBackground(new java.awt.Color(34, 167, 240));
        jButtonDeleteFromGiatros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteFromGiatros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteFromGiatros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonDeleteFromGiatros.setText("Διαγραφή");
        jButtonDeleteFromGiatros.setToolTipText("ΠΡΟΣΟΧΗ!!! Χρειάζεται να βάλετε μόνο το ID Γιατρού!!!");
        jButtonDeleteFromGiatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteFromGiatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteFromGiatrosActionPerformed(evt);
            }
        });

        jTextFieldPNumber.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldPNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPNumber.setForeground(new java.awt.Color(228, 241, 254));

        jTextFieldSpecialty.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldSpecialty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSpecialty.setForeground(new java.awt.Color(228, 241, 254));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Επώνυμο:");

        jTextFieldSurname.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSurname.setForeground(new java.awt.Color(228, 241, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jButtonInsertToGiatros)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonUpdateFromGiatros)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonDeleteFromGiatros)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonResetManageGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonExitPage))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertToGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetManageGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateFromGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteFromGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButtonExitPage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonResetManageGiatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetManageGiatrosActionPerformed
        jTextFieldDoctorID.setText("");
        jTextFieldSurname.setText("");
        jTextFieldName.setText("");
        jTextFieldPNumber.setText("");
        jTextFieldSpecialty.setText("");
    }//GEN-LAST:event_jButtonResetManageGiatrosActionPerformed

    private void jButtonExitPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitPageActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitPageActionPerformed

    private void jButtonInsertToGiatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertToGiatrosActionPerformed
        String surname = jTextFieldSurname.getText();
        String name = jTextFieldName.getText();
        String pnumber = jTextFieldPNumber.getText();
        String specialty = jTextFieldSpecialty.getText();

        if(surname.equals("") || name.equals("") || pnumber.equals("") || specialty.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Some Fields Are Empty!!!", "ERROR", 1);
        } else {

            try {
                String insertString = "INSERT INTO Giatros(Epwnymo, Onoma, Thlefwno, Eidikothta) \n" +
                "values(?,?,?,?)";
                pst = dbConnection.prepareStatement(insertString);
                pst.setString(1, surname);
                pst.setString(2, name);
                pst.setString(3, pnumber);
                pst.setString(4, specialty);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted Successfully!!!");
            } catch(SQLException ex) {
                System.out.println("\n -- SQL Exception --- \n");
                while(ex != null) {
                    System.out.println("Message: " + ex.getMessage());
                    ex = ex.getNextException();
                }
            }
        }
    }//GEN-LAST:event_jButtonInsertToGiatrosActionPerformed

    private void jButtonUpdateFromGiatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateFromGiatrosActionPerformed
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        String surname = jTextFieldSurname.getText();
        String name = jTextFieldName.getText();
        String pnumber = jTextFieldPNumber.getText();
        String specialty = jTextFieldSpecialty.getText();

        try {
            String updateString = "UPDATE Giatros SET Epwnymo=?, Onoma=?, " +
            "Thlefwno=?, Eidikothta=? WHERE IDGiatrou=?";
            pst = dbConnection.prepareStatement(updateString);
            pst.setInt(5, doctorID);
            pst.setString(1, surname);
            pst.setString(2, name);
            pst.setString(3, pnumber);
            pst.setString(4, specialty);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonUpdateFromGiatrosActionPerformed

    private void jButtonDeleteFromGiatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteFromGiatrosActionPerformed
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        // String surname = jTextFieldSurname.getText();
        // String name = jTextFieldName.getText();
        // String pnumber = jTextFieldPNumber.getText();
        // String specialty = jTextFieldSpecialty.getText();

        try {
            String deleteString = "DELETE FROM Giatros WHERE IDGiatrou=?";
            pst = dbConnection.prepareStatement(deleteString);
            pst.setInt(1, doctorID);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Deleted Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonDeleteFromGiatrosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGiatrosForm().setVisible(true);
            }
        });
    }
    
    static String     driverClassName = "oracle.jdbc.OracleDriver" ;
    static String     url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs" ;
    static Connection dbConnection = null;
    static String     username = "it144172";
    static String     passwd = "j@3teJi3";
    static PreparedStatement  pst = null;
    // static ResultSet rs = null;
    
    void myconnection() {
        try { 
             Class.forName (driverClassName);
        } catch (ClassNotFoundException ex) { }
        try {    
            dbConnection = DriverManager.getConnection (url, username, passwd);
            // String insertString = "INSERT INTO Kratisi(IDAstheni, IDGiatrou, HmeromhniaKratisis, OraKratisis) values(?,?,?,?)";
            // pst = dbConnection.prepareStatement(insertString);
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteFromGiatros;
    private javax.swing.JButton jButtonExitPage;
    private javax.swing.JButton jButtonInsertToGiatros;
    private javax.swing.JButton jButtonResetManageGiatros;
    private javax.swing.JButton jButtonUpdateFromGiatros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDoctorID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPNumber;
    private javax.swing.JTextField jTextFieldSpecialty;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
