import javax.swing.*;
import java.sql.*;
import javax.swing.JFrame;

public class ManageKratisiForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageKratisiForm
     */
    public ManageKratisiForm() {
        initComponents();
        myconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBackToKratisi = new javax.swing.JButton();
        jButtonInsertToKratisi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPatientID = new javax.swing.JTextField();
        jButtonResetManageKratisi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDoctorID = new javax.swing.JTextField();
        jComboBoxDate = new javax.swing.JComboBox();
        jComboBoxTime = new javax.swing.JComboBox();
        jButtonUpdateFromKratisi = new javax.swing.JButton();
        jButtonDeleteFromKratisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Διαχείριση Στοιχείων Κράτησης");

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMinimize))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jButtonBackToKratisi.setBackground(new java.awt.Color(149, 165, 166));
        jButtonBackToKratisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackToKratisi.setForeground(new java.awt.Color(242, 38, 19));
        jButtonBackToKratisi.setText("Επιστροφή στο Menu Κράτησης");
        jButtonBackToKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackToKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToKratisiActionPerformed(evt);
            }
        });

        jButtonInsertToKratisi.setBackground(new java.awt.Color(34, 167, 240));
        jButtonInsertToKratisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInsertToKratisi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertToKratisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonInsertToKratisi.setText("Εισαγωγή");
        jButtonInsertToKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsertToKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertToKratisiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("ID Ασθενή:");

        jTextFieldPatientID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldPatientID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPatientID.setForeground(new java.awt.Color(228, 241, 254));

        jButtonResetManageKratisi.setBackground(new java.awt.Color(242, 38, 19));
        jButtonResetManageKratisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResetManageKratisi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResetManageKratisi.setText("Reset");
        jButtonResetManageKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonResetManageKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetManageKratisiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("ID Γιατρού:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Ημερομηνία:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Ώρα:");

        jTextFieldDoctorID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldDoctorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDoctorID.setForeground(new java.awt.Color(228, 241, 254));

        jComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "28/05/18", "29/05/18", "30/05/18", "31/05/18", "01/05/18", "02/05/18", "03/06/18", "04/06/18", "05/06/18", "06/06/18", "07/06/18", "08/06/18", "09/06/18", "10/06/18" }));

        jComboBoxTime.setMaximumRowCount(5);
        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00" }));

        jButtonUpdateFromKratisi.setBackground(new java.awt.Color(34, 167, 240));
        jButtonUpdateFromKratisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateFromKratisi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateFromKratisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButtonUpdateFromKratisi.setText("Ενημέρωση");
        jButtonUpdateFromKratisi.setToolTipText("ΠΡΟΣΟΧΗ!!! Η Ενημέρωση γίνεται με βάση το ID Ασθενή και το ID Γιατρού!!!");
        jButtonUpdateFromKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdateFromKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateFromKratisiActionPerformed(evt);
            }
        });

        jButtonDeleteFromKratisi.setBackground(new java.awt.Color(34, 167, 240));
        jButtonDeleteFromKratisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteFromKratisi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteFromKratisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonDeleteFromKratisi.setText("Διαγραφή");
        jButtonDeleteFromKratisi.setToolTipText("ΠΡΟΣΟΧΗ!!! Χρειάζεται να βάλετε ΟΛΑ τα πεδία!!!");
        jButtonDeleteFromKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteFromKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteFromKratisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPatientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInsertToKratisi)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonUpdateFromKratisi)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonDeleteFromKratisi)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonResetManageKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBackToKratisi))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertToKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetManageKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateFromKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteFromKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButtonBackToKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonResetManageKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetManageKratisiActionPerformed
        jTextFieldPatientID.setText("");
        jTextFieldDoctorID.setText("");
    }//GEN-LAST:event_jButtonResetManageKratisiActionPerformed

    private void jButtonBackToKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToKratisiActionPerformed
        KratisiForm kf = new KratisiForm();
        kf.setVisible(true);
        kf.pack();
        kf.setLocationRelativeTo(null);
        kf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBackToKratisiActionPerformed

    private void jButtonInsertToKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertToKratisiActionPerformed
        int patientID = Integer.valueOf(jTextFieldPatientID.getText());
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        String date = jComboBoxDate.getSelectedItem().toString();
        String time = jComboBoxTime.getSelectedItem().toString();
        
        /*
        if((jTextFieldPatientID.getText().isEmpty()) || (jTextFieldDoctorID.getText().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Some Fields Are Empty!!!", "ERROR", 1);
        } else {
        */
        
            try {
                String insertString = "INSERT INTO Kratisi(IDAstheni, IDGiatrou, HmeromhniaKratisis, OraKratisis) values(?,?,?,?)";
                pst = dbConnection.prepareStatement(insertString);
                pst.setInt(1, patientID);
                pst.setInt(2, doctorID);
                pst.setString(3, date);
                pst.setString(4, time);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted Successfully!!!");
            } catch(SQLException ex) {
                 System.out.println("\n -- SQL Exception --- \n");
                 while(ex != null) {
                     System.out.println("Message: " + ex.getMessage());
                     ex = ex.getNextException();
                 }
             }
        // }
    }//GEN-LAST:event_jButtonInsertToKratisiActionPerformed

    private void jButtonUpdateFromKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateFromKratisiActionPerformed
        int patientID = Integer.valueOf(jTextFieldPatientID.getText());
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        String date = jComboBoxDate.getSelectedItem().toString();
        String time = jComboBoxTime.getSelectedItem().toString();
        
        try {
            String updateString = "UPDATE Kratisi SET HmeromhniaKratisis=?, " +
                              "OraKratisis=? WHERE IDAstheni=? AND IDGiatrou=?";
            pst = dbConnection.prepareStatement(updateString);
            pst.setInt(3, patientID);
            pst.setInt(4, doctorID);
            pst.setString(1, date);
            pst.setString(2, time);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
                 while(ex != null) {
                     System.out.println("Message: " + ex.getMessage());
                     ex = ex.getNextException();
                 }
        }
    }//GEN-LAST:event_jButtonUpdateFromKratisiActionPerformed

    private void jButtonDeleteFromKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteFromKratisiActionPerformed
        int patientID = Integer.valueOf(jTextFieldPatientID.getText());
        int doctorID = Integer.valueOf(jTextFieldDoctorID.getText());
        String date = jComboBoxDate.getSelectedItem().toString();
        String time = jComboBoxTime.getSelectedItem().toString();
        
        try {
            String updateString = "DELETE FROM Kratisi WHERE IDAstheni=? " +
                    "AND IDGiatrou=? AND HmeromhniaKratisis=? AND OraKratisis=?";
            pst = dbConnection.prepareStatement(updateString);
            pst.setInt(1, patientID);
            pst.setInt(2, doctorID);
            pst.setString(3, date);
            pst.setString(4, time);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Deleted Successfully!!!");
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
                 while(ex != null) {
                     System.out.println("Message: " + ex.getMessage());
                     ex = ex.getNextException();
                 }
        }
    }//GEN-LAST:event_jButtonDeleteFromKratisiActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageKratisiForm().setVisible(true);
            }
        });
    }
    
    static String     driverClassName = "oracle.jdbc.OracleDriver" ;
    static String     url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs" ;
    static Connection dbConnection = null;
    static String     username = "it144172";
    static String     passwd = "j@3teJi3";
    static PreparedStatement  pst = null;
    // static ResultSet rs = null;
    
    void myconnection() {
        try { 
             Class.forName (driverClassName);
        } catch (ClassNotFoundException ex) { }
        try {    
            dbConnection = DriverManager.getConnection (url, username, passwd);
            // String insertString = "INSERT INTO Kratisi(IDAstheni, IDGiatrou, HmeromhniaKratisis, OraKratisis) values(?,?,?,?)";
            // pst = dbConnection.prepareStatement(insertString);
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToKratisi;
    private javax.swing.JButton jButtonDeleteFromKratisi;
    private javax.swing.JButton jButtonInsertToKratisi;
    private javax.swing.JButton jButtonResetManageKratisi;
    private javax.swing.JButton jButtonUpdateFromKratisi;
    private javax.swing.JComboBox jComboBoxDate;
    private javax.swing.JComboBox jComboBoxTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDoctorID;
    private javax.swing.JTextField jTextFieldPatientID;
    // End of variables declaration//GEN-END:variables
}
