import javax.swing.JFrame;
import java.sql.*;

public class ProswpikoExecuteQueries extends javax.swing.JFrame {

    /**
     * Creates new form ProswpikoExecuteQueries
     */
    public ProswpikoExecuteQueries() {
        initComponents();
        myconnection();
        /*
        1. Type &nbsp; to add one space.
        2. Type &ensp; to add two spaces.
        3. Type &emsp; to add four spaces.
        */
        jLabel2.setText("<html>ΚΑΝΤΕ ΚΛΙΚ ΓΙΑ ΕΚΤΕΛΕΣΗ ΣΤΑΤΙΚΩΝ/ΔΥΝΑΜΙΚΩΝ" +
                "<br>&emsp;&emsp;&emsp;&emsp;" +
                "&emsp;&emsp;&emsp;&emsp;ΕΡΩΤΗΜΑΤΩΝ SQL</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFirstDynamicQuery = new javax.swing.JButton();
        jButtonThirdDynamicQuery = new javax.swing.JButton();
        jButtonSecondDynamicQuery = new javax.swing.JButton();
        jButtonSecondStaticQuery = new javax.swing.JButton();
        jButtonThirdStaticQuery = new javax.swing.JButton();
        jButtonFirstStaticQuery = new javax.swing.JButton();
        jButtonExitPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Προσωπικό: ");

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMinimize))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(486, 420));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ΕΠΙΚΕΦΑΛΙΔΑ");

        jButtonFirstDynamicQuery.setBackground(new java.awt.Color(0, 84, 118));
        jButtonFirstDynamicQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFirstDynamicQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFirstDynamicQuery.setText("1o ΔΥΝΑΜΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonFirstDynamicQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFirstDynamicQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstDynamicQueryActionPerformed(evt);
            }
        });

        jButtonThirdDynamicQuery.setBackground(new java.awt.Color(0, 84, 118));
        jButtonThirdDynamicQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonThirdDynamicQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThirdDynamicQuery.setText("3ο ΔΥΝΑΜΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonThirdDynamicQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThirdDynamicQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThirdDynamicQueryActionPerformed(evt);
            }
        });

        jButtonSecondDynamicQuery.setBackground(new java.awt.Color(0, 84, 118));
        jButtonSecondDynamicQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSecondDynamicQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSecondDynamicQuery.setText("2ο ΔΥΝΑΜΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonSecondDynamicQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSecondDynamicQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecondDynamicQueryActionPerformed(evt);
            }
        });

        jButtonSecondStaticQuery.setBackground(new java.awt.Color(38, 166, 91));
        jButtonSecondStaticQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSecondStaticQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSecondStaticQuery.setText("2ο ΣΤΑΤΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonSecondStaticQuery.setToolTipText("Βρες το ονοματεπώνυμο του Γιατρου που έχει μόνο ένα άτομο για Προσωπικό");
        jButtonSecondStaticQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSecondStaticQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecondStaticQueryActionPerformed(evt);
            }
        });

        jButtonThirdStaticQuery.setBackground(new java.awt.Color(38, 166, 91));
        jButtonThirdStaticQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonThirdStaticQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThirdStaticQuery.setText("3ο ΣΤΑΤΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonThirdStaticQuery.setToolTipText("Βρες το ονοματεπώνυμο του Προσωπικού που έχει το username 'iwancho'");
        jButtonThirdStaticQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThirdStaticQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThirdStaticQueryActionPerformed(evt);
            }
        });

        jButtonFirstStaticQuery.setBackground(new java.awt.Color(38, 166, 91));
        jButtonFirstStaticQuery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFirstStaticQuery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFirstStaticQuery.setText("1ο ΣΤΑΤΙΚΟ ΕΡΩΤΗΜΑ");
        jButtonFirstStaticQuery.setToolTipText("Βρες το ονοματεπώνυμο και την ειδικότητα του Γιατρού που έχει σαν προσωπικό Γραμματέα και Νοσοκόμα");
        jButtonFirstStaticQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFirstStaticQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstStaticQueryActionPerformed(evt);
            }
        });

        jButtonExitPage.setBackground(new java.awt.Color(149, 165, 166));
        jButtonExitPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExitPage.setForeground(new java.awt.Color(242, 38, 19));
        jButtonExitPage.setText("Έξοδος απ' τη σελίδα");
        jButtonExitPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExitPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExitPage)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonFirstDynamicQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSecondDynamicQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThirdDynamicQuery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSecondStaticQuery, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(jButtonThirdStaticQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonFirstStaticQuery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFirstDynamicQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFirstStaticQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSecondDynamicQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSecondStaticQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThirdStaticQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThirdDynamicQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButtonExitPage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonExitPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitPageActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitPageActionPerformed

    private void jButtonFirstDynamicQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstDynamicQueryActionPerformed
        Proswpiko_First_Dynamic_Query pfdq = new Proswpiko_First_Dynamic_Query();
        pfdq.setVisible(true);
        pfdq.pack();
        pfdq.setLocationRelativeTo(null);
        pfdq.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonFirstDynamicQueryActionPerformed

    private void jButtonSecondDynamicQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecondDynamicQueryActionPerformed
        Proswpiko_Second_Dynamic_Query psdq = new Proswpiko_Second_Dynamic_Query();
        psdq.setVisible(true);
        psdq.pack();
        psdq.setLocationRelativeTo(null);
        psdq.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonSecondDynamicQueryActionPerformed

    private void jButtonFirstStaticQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstStaticQueryActionPerformed
        try {
            // Δημιουργία αντικειμένου Statement
            stmt = dbConnection.createStatement();
            String selectQuery = "SELECT G.Onoma, G.Epwnymo, G.Eidikothta\n" +
                                 "FROM Exei E INNER JOIN Giatros G ON E.IDGiatrou=G.IDGiatrou\n" +
                                 "INNER JOIN Proswpiko P ON E.IDProswpikou=P.IDProswpikou\n" +
                                 "WHERE P.Thesi='Γραμματέας'\n" +
                                 "INTERSECT\n" +
                                 "SELECT G.Onoma, G.Epwnymo, G.Eidikothta\n" +
                                 "FROM Exei E INNER JOIN Giatros G ON E.IDGiatrou=G.IDGiatrou\n" +
                                 "INNER JOIN Proswpiko P ON E.IDProswpikou=P.IDProswpikou\n" +
                                 "WHERE P.Thesi='Νοσοκόμα'";
            rs = stmt.executeQuery(selectQuery);
            System.out.println("ΟΝΟΜΑ ΓΙΑΤΡΟΥ       ΕΠΩΝΥΜΟ ΓΙΑΤΡΟΥ       ΕΙΔΙΚΟΤΗΤΑ" );
            while(rs.next()) {
                String gname = rs.getString("Onoma");
                String gsurname = rs.getString("Epwnymo");
                String specialty = rs.getString("Eidikothta");
                System.out.println(gname + "            " + gsurname + "                 " + specialty);
            }
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonFirstStaticQueryActionPerformed

    private void jButtonSecondStaticQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecondStaticQueryActionPerformed
        try {
            // Δημιουργία αντικειμένου Statement
            stmt = dbConnection.createStatement();
            String selectQuery = "SELECT G.Onoma, G.Epwnymo\n" +
                                 "FROM Giatros G\n" +
                                 "WHERE 1=(SELECT COUNT(*)\n" +
                                 "FROM Exei E, Proswpiko P\n" +
                                 "WHERE E.IDGiatrou=G.IDGiatrou\n" +
                                 "AND E.IDProswpikou=P.IDProswpikou)";
            rs = stmt.executeQuery(selectQuery);
            System.out.println("ΟΝΟΜΑ ΓΙΑΤΡΟΥ       ΕΠΩΝΥΜΟ ΓΙΑΤΡΟΥ" );
            while(rs.next()) {
                String name = rs.getString("Onoma");
                String surname = rs.getString("Epwnymo");
                System.out.println(name + "               " + surname);
            }
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonSecondStaticQueryActionPerformed

    private void jButtonThirdStaticQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThirdStaticQueryActionPerformed
        try {
            // Δημιουργία αντικειμένου Statement
            stmt = dbConnection.createStatement();
            String selectQuery = "SELECT P.onoma, P.epwnymo\n" +
                                 "FROM Proswpiko P INNER JOIN Login L ON P.username=L.username\n" +
                                 "WHERE P.username='iwancho'";
            rs = stmt.executeQuery(selectQuery);
            System.out.println("ΟΝΟΜΑ ΠΡΟΣΩΠΙΚΟΥ      ΕΠΩΝΥΜΟ ΠΡΟΣΩΠΙΚΟΥ" );
            while(rs.next()) {
                String name = rs.getString("onoma");
                String surname = rs.getString("epwnymo");
                System.out.println(name + "                " + surname);
            }
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }//GEN-LAST:event_jButtonThirdStaticQueryActionPerformed

    private void jButtonThirdDynamicQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThirdDynamicQueryActionPerformed
        Proswpiko_Third_Dynamic_Query ptdq = new Proswpiko_Third_Dynamic_Query();
        ptdq.setVisible(true);
        ptdq.pack();
        ptdq.setLocationRelativeTo(null);
        ptdq.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonThirdDynamicQueryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProswpikoExecuteQueries().setVisible(true);
            }
        });
    }
    
    static String     driverClassName = "oracle.jdbc.OracleDriver" ;
    static String     url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs" ;
    static Connection dbConnection = null;
    static String     username = "it144172";
    static String     passwd = "j@3teJi3";
    static Statement  stmt = null;
    static ResultSet rs = null;
    
    void myconnection() {
        try { 
             Class.forName (driverClassName);
        } catch (ClassNotFoundException ex) { }
        try {    
            dbConnection = DriverManager.getConnection (url, username, passwd);
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
		System.out.println("Message: " + ex.getMessage());
		ex = ex.getNextException();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExitPage;
    private javax.swing.JButton jButtonFirstDynamicQuery;
    private javax.swing.JButton jButtonFirstStaticQuery;
    private javax.swing.JButton jButtonSecondDynamicQuery;
    private javax.swing.JButton jButtonSecondStaticQuery;
    private javax.swing.JButton jButtonThirdDynamicQuery;
    private javax.swing.JButton jButtonThirdStaticQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
