import javax.swing.JFrame;

public class ProswpikoForm extends javax.swing.JFrame {

    /**
     * Creates new form ProswpikoForm
     */
    public ProswpikoForm(String uname) {
        initComponents();
        jLabel1.setText("Welcome " +jLabel1.getText() + uname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        jButtonManageAsthenis = new javax.swing.JButton();
        jButtonExei = new javax.swing.JButton();
        jButtonKratisi = new javax.swing.JButton();
        jButtonManageProswpiko = new javax.swing.JButton();
        jButtonManageAccount = new javax.swing.JButton();
        jButtonManageGiatros = new javax.swing.JButton();
        jButtonExecuteQueries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Προσωπικό: ");

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMinimize))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jButtonLogout.setBackground(new java.awt.Color(242, 38, 19));
        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonManageAsthenis.setBackground(new java.awt.Color(240, 52, 52));
        jButtonManageAsthenis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonManageAsthenis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageAsthenis.setText("ΔΙΑΧΕΙΡΙΣΗ ΑΣΘΕΝΗ");
        jButtonManageAsthenis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageAsthenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageAsthenisActionPerformed(evt);
            }
        });

        jButtonExei.setBackground(new java.awt.Color(148, 124, 176));
        jButtonExei.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExei.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExei.setText("ΔΙΑΧΕΙΡΙΣΗ ΠΙΝΑΚΑ ΕΧΕΙ");
        jButtonExei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExeiActionPerformed(evt);
            }
        });

        jButtonKratisi.setBackground(new java.awt.Color(243, 156, 18));
        jButtonKratisi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonKratisi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKratisi.setText("ΔΙΑΧΕΙΡΙΣΗ ΚΡΑΤΗΣΗΣ");
        jButtonKratisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKratisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKratisiActionPerformed(evt);
            }
        });

        jButtonManageProswpiko.setBackground(new java.awt.Color(108, 199, 249));
        jButtonManageProswpiko.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonManageProswpiko.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageProswpiko.setText("ΔΙΑΧΕΙΡΙΣΗ ΠΡΟΣΩΠΙΚΟΥ");
        jButtonManageProswpiko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageProswpiko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageProswpikoActionPerformed(evt);
            }
        });

        jButtonManageAccount.setBackground(new java.awt.Color(0, 84, 118));
        jButtonManageAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonManageAccount.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageAccount.setText("ΔΙΑΧΕΙΡΙΣΗ ΛΟΓΑΡΙΑΣΜΟΥ");
        jButtonManageAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageAccountActionPerformed(evt);
            }
        });

        jButtonManageGiatros.setBackground(new java.awt.Color(65, 131, 215));
        jButtonManageGiatros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonManageGiatros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageGiatros.setText("ΔΙΑΧΕΙΡΙΣΗ ΓΙΑΤΡΟΥ");
        jButtonManageGiatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageGiatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageGiatrosActionPerformed(evt);
            }
        });

        jButtonExecuteQueries.setBackground(new java.awt.Color(38, 166, 91));
        jButtonExecuteQueries.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExecuteQueries.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExecuteQueries.setText("ΕΚΤΕΛΕΣΗ ΣΤΑΤΙΚΩΝ/ΔΥΝΑΜΙΚΩΝ ΕΡΩΤΗΜΑΤΩΝ SQL");
        jButtonExecuteQueries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecuteQueries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecuteQueriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonManageProswpiko, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jButtonKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonManageAsthenis, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonManageAccount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExei, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonManageGiatros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonExecuteQueries)
                        .addGap(120, 120, 120))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManageGiatros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonManageAsthenis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExei, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonManageProswpiko, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKratisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonExecuteQueries, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        LoginForm lf = new LoginForm();
        // Κλείνω τελείως όλο το παράθυρό μου (το frame που βρίσκομαι αυτή τη στιγμή)
        dispose();
        lf.main(null); // Το βάζω για να σβήνονται αυτά που έχω γράψει
                       // στο username και password και να εμφανιστεί το LoginForm
                       // Αν το σβήσω, τρέχει ακόμα το πρόγραμμα και
                       // δε με εμφανίζει τίποτα

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageAccountActionPerformed
        ManageAccountForm maf = new ManageAccountForm();
        // Λέω στο καινούργιο μου jFrame να εμφανιστεί στην οθόνη
        maf.setVisible(true);
        // Φτιάχνω το μέγεθος του frame μου ώστε να με χωράει ανεξαρτήτως
        // (στο μικρότερο δυνατό μέγεθος) τα δεδομένα που θα του έχω βάλει
        maf.pack();
        // Το κανω για να μου εμφανίζει το frame που μεταφέρομαι στη μέση
        // ανεξαρτήτως (το βάζω έτσι κι αλλιώς)
        maf.setLocationRelativeTo(null);
        // ΜΕ ΤΟ ΠΟΥ ΠΑΤΗΣΩ ΤΟ ΚΟΚΚΙΝΟ " Χ " ΣΤΗΝ ΕΦΑΡΜΟΓΗ ΜΟΥ ΝΑ ΣΤΑΜΑΤΗΣΕΙ
        // ΝΑ ΤΡΕΧΕΙ ΤΟ ΠΡΟΓΡΑΜΜΑ ΣΤΟ ΚΑΙΝΟΥΡΓΙΟ ΜΟΥ FRAME!!!!!
        maf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonManageAccountActionPerformed

    private void jButtonManageAsthenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageAsthenisActionPerformed
        ManageAsthenisForm masf = new ManageAsthenisForm();
        masf.setVisible(true);
        masf.pack();
        masf.setLocationRelativeTo(null);
        masf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonManageAsthenisActionPerformed

    private void jButtonManageProswpikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageProswpikoActionPerformed
        ManageProswpikoForm mpf = new ManageProswpikoForm();
        mpf.setVisible(true);
        mpf.pack();
        mpf.setLocationRelativeTo(null);
        mpf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonManageProswpikoActionPerformed

    private void jButtonManageGiatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageGiatrosActionPerformed
        ManageGiatrosForm mgf = new ManageGiatrosForm();
        mgf.setVisible(true);
        mgf.pack();
        mgf.setLocationRelativeTo(null);
        mgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonManageGiatrosActionPerformed

    private void jButtonExeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExeiActionPerformed
        ExeiForm ef = new ExeiForm();
        ef.setVisible(true);
        ef.pack();
        ef.setLocationRelativeTo(null);
        ef.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonExeiActionPerformed

    private void jButtonKratisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKratisiActionPerformed
        KratisiForm kf = new KratisiForm();
        kf.setVisible(true);
        kf.pack();
        kf.setLocationRelativeTo(null);
        kf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonKratisiActionPerformed

    private void jButtonExecuteQueriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecuteQueriesActionPerformed
        ProswpikoExecuteQueries peq = new ProswpikoExecuteQueries();
        peq.setVisible(true);
        peq.pack();
        peq.setLocationRelativeTo(null);
        peq.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonExecuteQueriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecuteQueries;
    private javax.swing.JButton jButtonExei;
    private javax.swing.JButton jButtonKratisi;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonManageAccount;
    private javax.swing.JButton jButtonManageAsthenis;
    private javax.swing.JButton jButtonManageGiatros;
    private javax.swing.JButton jButtonManageProswpiko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
